# Generated by Django 2.0.3 on 2019-11-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetailApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='code',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='fname',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
