# Generated by Django 2.0.3 on 2019-11-14 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetailApp', '0004_auto_20191114_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='phone',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
