# Generated by Django 2.0.3 on 2019-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpDetailApp', '0006_auto_20191114_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='email',
            field=models.EmailField(default='invalid@gmail.com', max_length=45),
        ),
    ]
